[package]
name = "staging-chain-spec-builder"
version = "3.0.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
path = "bin/main.rs"
name = "chain-spec-builder"

[lib]
crate-type = ["rlib"]

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
log = { workspace = true, default-features = true }
sc-chain-spec = {  git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
serde_json = { workspace = true, default-features = true }
sp-tracing = {  git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
